-- ==========================================================
-- LEVEL 4A : INTERMEDIATE SQL
-- ==========================================================

-- ==========================================================
-- Query 1 : Average Revenue by Campaign
-- Business Question:
-- What is the average revenue generated by each campaign?
-- ==========================================================

SELECT
    campaign_name,
    ROUND(AVG(revenue_generated),2) AS average_revenue
FROM marketing_performance
GROUP BY campaign_name
ORDER BY average_revenue DESC;

-- ==========================================================
-- Query 2 : Highest and Lowest Revenue
-- Business Question:
-- What are the highest and lowest revenues generated by each campaign?
-- ==========================================================

SELECT
    campaign_name,
    MAX(revenue_generated) AS highest_revenue,
    MIN(revenue_generated) AS lowest_revenue
FROM marketing_performance
GROUP BY campaign_name
ORDER BY highest_revenue DESC;

-- ==========================================================
-- Query 3 : Above Average Revenue
-- Business Question:
-- Which campaign records generated above-average revenue?
-- ==========================================================

SELECT *
FROM marketing_performance
WHERE revenue_generated >
(
    SELECT AVG(revenue_generated)
    FROM marketing_performance
)
ORDER BY revenue_generated DESC;

-- ==========================================================
-- Query 4 : High ROAS Campaigns
-- Business Question:
-- Which campaign records achieved a ROAS greater than 3?
-- ==========================================================

SELECT *
FROM marketing_performance
WHERE roas > 3
ORDER BY roas DESC;

-- ==========================================================
-- Query 5 : Campaign Count by Channel
-- Business Question:
-- How many campaigns were run through each marketing channel?
-- ==========================================================

SELECT
    channel,
    COUNT(*) AS total_campaigns
FROM marketing_performance
GROUP BY channel
ORDER BY total_campaigns DESC;

-- ==========================================================
-- Query 6 : Distinct Campaign Names
-- Business Question:
-- What are the unique campaign names?
-- ==========================================================

SELECT DISTINCT campaign_name
FROM marketing_performance
ORDER BY campaign_name;

-- ==========================================================
-- Query 7 : Revenue Category
-- Business Question:
-- Categorize campaigns based on revenue generated.
-- ==========================================================

SELECT
    campaign_name,
    revenue_generated,

    CASE
        WHEN revenue_generated >= 10000 THEN 'High Revenue'
        WHEN revenue_generated >= 5000 THEN 'Medium Revenue'
        ELSE 'Low Revenue'
    END AS revenue_category

FROM marketing_performance;

-- ==========================================================
-- Query 8 : High Revenue Channels
-- Business Question:
-- Which marketing channels generated more than 4 million revenue?
-- ==========================================================

SELECT
    channel,
    ROUND(SUM(revenue_generated),2) AS total_revenue
FROM marketing_performance
GROUP BY channel
HAVING total_revenue > 4000000
ORDER BY total_revenue DESC;

-- ==========================================================
-- Query 9 : Average CTR by Channel
-- Business Question:
-- What is the average Click Through Rate (CTR) for each marketing channel?
-- ==========================================================

SELECT
    channel,
    ROUND((SUM(clicks) * 100.0) / SUM(impressions), 2) AS average_ctr
FROM marketing_performance
GROUP BY channel
ORDER BY average_ctr DESC;

-- ==========================================================
-- Query 10 : Average ROAS by Target Audience
-- Business Question:
-- Which target audience has the highest average ROAS?
-- ==========================================================

SELECT
    target_audience,
    ROUND(SUM(revenue_generated) / SUM(spend), 2) AS average_roas
FROM marketing_performance
GROUP BY target_audience
ORDER BY average_roas DESC;